spring:
  application:
    name: template-microservice
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:h2:mem:RepositoryTestDb;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: DEBUG
  file: log.txt

flyway:
  enabled: true
  schemas: TestSchema
  locations: classpath:/sql

server:
  port: ${PORT:3333}


